### ISSUE TITLE
delete and fork from eAtlas

### ISSUE THREAD

**Issue by layik** [saferactive/saferactive-eatlas#1]
I will delete (or create another repo) from the original repo and apply the changes and commit. Should have done that when we first set this repo up.

**Comment by Robinlovelace** [comment]
Or to minimise duplication of code could the new package start with 

```
npm install -g eatlas
```
or 

```r
remotes::install_github("atfutures/geoplumber")
```

or similar so we pull in the generic code and focus on developing the project specific code without needing to fork code-bases and deal with divergence.

**Comment by layik** [comment]
```
git clone saferactive/eatlas
Rscript run.R
# if no prior build then
geoplumber::build() # which is where npm does its bits
# then Rscript run.R
```

**Comment by Robinlovelace** [comment]
:+1: sounds like a good starting point that avoids duplicating code but wondering if code from eAtlas that could be useful for SaferActive could be useful for other projects and be worth putting in `geoplumber`, the generalisable parts. If not starting with eAtlas sounds good, but I imagine the changes to the UI will make this project quite different at some point. A diverging fork of eAtlas code is also fine I guess. Thinking out loud or as typing at least!

**Comment by layik** [comment]
No need at this point. Robin's suggestion is now implemented, documentation later.
