### ISSUE TITLE
Adding Local Authority polygons

### ISSUE THREAD

**Issue by Robinlovelace** [saferactive/saferactive-eatlas#10]
And associated results shown here: https://github.com/saferactive/saferactive/issues/8

Doable as an overlay?

**Comment by layik** [comment]
This is doable of course. Will probably be second stage now, first deployment would consider a "certain" zoom level. #15

**Comment by layik** [comment]
Are we doing this? Including the risk bars in the draft paper or any other LA polygons.

**Comment by Robinlovelace** [comment]
Low priority atm and that's the 'zoomed out' module.
