### ISSUE TITLE
Minimum data requirements to show

### ISSUE THREAD

**Issue by Robinlovelace** [saferactive/saferactive-eatlas#12]
The framework works and is looking very good. I think it's worth considering the minimum data requirements we want before making this publicly available as an attractive service. This can be an evolving 'must have' and wish list that we can discuss below.

### Must have

- [x] Show individual crashes beyond a certain zoom level (for feature parity with https://www.crashmap.co.uk/Search )
- [x] Show key attributes (when available - TBC) of individual crashes
- [x] Remove Stamen basemap and use API key for map tiles (not for profit) - easy
- [x] Heat map style map of crash numbers
- [x]  Allow user to subset crashes shown by attribute (primarily severity and casualty type in the test data)
- [ ] Show zone level results, primarily crash risk estimates per billion km at the borough level e.g. building on #10 
- [x] Attribute graphics that respond to zooming/panning and ideally selection of polygons
- [x] Update the input data - Greater London area, up-to-date (2009 - 2018) casualty data 

### Nice to have

- [ ] Responsive 'diameter' slider with 'metres' in the legend title
- [ ] Cycling uptake levels (RL and JT to do)
- [x] Time slider
- [ ] Upset plots in the window
- [x] Data downloads associated with current map
- [ ] Polygon selection tool
- [x] Demo of national scalability

Thoughts @layik ? This is clearly not all doable at once and we need to provide geoplumber with more data before it is but think it's a good starter for a direction of travel.

**Comment by layik** [comment]
Great features to add here.

**Comment by layik** [comment]
Reopen or separate list items if need be. I think I can close this ticket.
