### ISSUE TITLE
Visualising crashes over time

### ISSUE THREAD

**Issue by Robinlovelace** [saferactive/saferactive-eatlas#13]
I recall we had this in an earlier version. Currently I can only get it to show individual dates rather than change over time with the x axis being weeks/months:

![image](https://user-images.githubusercontent.com/1825120/88316324-8d79e180-cd0f-11ea-802e-298de8258b8d.png)

Doable? I think this may be another 'must have' for #12. Sorry for all the issues @layik, just thinking about it and wanting to get my thoughts down in a useful way.

**Comment by layik** [comment]
doable after #18

**Comment by layik** [comment]
The only thing left to do here is whether annual breakdown is enough.

**Comment by Robinlovelace** [comment]
> The only thing left to do here is whether annual breakdown is enough.

I think so, although may be worth adding Season, Month, hour, day of week. The last of those two may already be in the data. But that's a separate (data processing) issue and not a blocker preventing this being closed (ideally when it's deployed).

**Comment by layik** [comment]
Sure thing! Just after actions finish running.

**Comment by layik** [comment]
<img width="294" alt="Screenshot 2021-01-15 at 11 20 31" src="https://user-images.githubusercontent.com/408568/104719010-b8c01500-5723-11eb-98d0-d76d0fe3d1c0.png">

Can visualize whatever we need. Closing for now.
