### ISSUE TITLE
UI not showing Cycling

### ISSUE THREAD

**Issue by Robinlovelace** [saferactive/saferactive-eatlas#16]
Currently I see this in the UI:

![image](https://user-images.githubusercontent.com/1825120/96987627-2e4c8880-151b-11eb-982e-28d7680eff92.png)

I think 'Active travel', 'Walking' and 'Cycling' could be in in place of that - various UI tweaks but this could be a good starter I think.

**Comment by layik** [comment]
Yep, no tiles to serve yet. This will change as you say.

**Comment by Robinlovelace** [comment]
OK but can we put 'Walking', 'Cycling' there as placeholders?

**Comment by layik** [comment]
placeholder in, close after a little tweak.

**Comment by layik** [comment]
done
