### ISSUE TITLE
Load time

### ISSUE THREAD

**Issue by Robinlovelace** [saferactive/saferactive-eatlas#18]
Several seconds on my computer.

**Comment by layik** [comment]
We can blame `sf` but we are sending 100k values over. Expected but yes noted.

**Comment by layik** [comment]
Loading less now, check and close if happy :)

**Comment by Robinlovelace** [comment]
Thanks @layik I've just double checked and it seems to be more than 10s on my computer, as shown in the gif below. Can you reproduce these load times? I think less than 5s is ideal. Could it not load any data, and at least show an interactive map, if zoomed out beyond a certain amount?

![Peek 2021-01-09 13-32](https://user-images.githubusercontent.com/1825120/104093003-8f187100-527f-11eb-8a63-3f3b50a1eb46.gif)

**Comment by layik** [comment]
So since previous comment, now loading excess of 32k rows, will try a couple of tricks using pioritised fields from #25 but might just have to load some 10k and should drop to 2s.

**Comment by layik** [comment]
Noted, next task after adapting slider for current dataset date format.

**Comment by layik** [comment]
```sh
$ time curl localhost:8000/api/stats19/0/0/0/0 > /dev/null 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 7679k  100 7679k    0     0  17.3M      0 --:--:-- --:--:-- --:--:-- 17.2M

real	0m0.448s
```

@Robinlovelace, with 10k points and 23 columns as plain geojson (more opts is still possible) but even as is that is the local response, we will measure the remote once we send this to the current deployment.

**Comment by Robinlovelace** [comment]
Looking good!

**Comment by layik** [comment]
The problem I see with this `subset <- dt[sample(nrow(dt), limit),]` is that it makes the data synthetic rather than real, so another method is needed. Maybe just going back to the area based subsetting @Robinlovelace.

**Comment by layik** [comment]
@Robinlovelace checkout https://map.saferactive.org

**Comment by Robinlovelace** [comment]
Still slow for me. Fun story, tried loading multiple times and it crashed the computer! Probably fast enough for now, not sure how we can make it faster. Can do another gif and time it for objective test.

**Comment by layik** [comment]
One thing that is done outside the app is "zip"ing the json served, we also have `pbf` which really should have been part of eAtlas for months now.

**Comment by layik** [comment]
Just reversed the sampling back to a sample boundary. Is this acceptable? 

```
$ time curl https://map.saferactive.org/api/stats19/0/0/0/0 > ~/Downloads/json.json 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 6009k  100 6009k    0     0  4320k      0  0:00:01  0:00:01 --:--:-- 4320k
```
Zipping module config on Apache next.

**Comment by layik** [comment]
As for the crash, latest changes _might_ be causing it. Will fix, once identified. There should be 0 crashes.

**Comment by Robinlovelace** [comment]
> As for the crash, latest changes _might_ be causing it. Will fix, once identified. There should be 0 crashes.

Think it was just memory, was on a computer with limited (4 or 8 Gb) RAM.

**Comment by layik** [comment]
ping @Robinlovelace

**Comment by layik** [comment]
`gzip` enabled before & after. Do not have an answer why after is still 1s+.

<img width="701" alt="Screenshot 2021-01-12 at 15 17 48" src="https://user-images.githubusercontent.com/408568/104333685-71e6db00-54e9-11eb-9673-19be2f140a06.png">
<img width="713" alt="Screenshot 2021-01-12 at 15 18 00" src="https://user-images.githubusercontent.com/408568/104333693-73180800-54e9-11eb-8303-7f6efa502b3c.png">

**Comment by layik** [comment]
@mem48 maybe `json` (geojson in our case) is not horrible.

**Comment by mem48** [comment]
I'm getting an odd effect where only some crash data is loading

![image](https://user-images.githubusercontent.com/15819577/104336439-5204e680-54ec-11eb-9ab2-500a1e247cd4.png)

**Comment by layik** [comment]
@mem48 yep, how can I specify a region? Custom polygon? At the moment, it picks the boundaries of the total data and then shrinks it by some factor. I tried sampling (say 10k) that makes the data "synthetic".

**Comment by layik** [comment]
here @mem48 
https://github.com/saferactive/saferactive-eatlas/blob/a657933bd13789a640505ce7f8503019a8340c8f/R/plumber.R#L100

**Comment by mem48** [comment]
So you have only loaded a little bit of south London?

**Comment by layik** [comment]
Yes, but trying to find a better way of doing it.

**Comment by layik** [comment]
Again reopen if still not happy with time, not clipping which is an issue.

**Comment by Robinlovelace** [comment]
Just checked and saw the new message to zoom in here: https://map.saferactive.org/?lat=51.324&lng=-0.297&zoom=10.00&bea=0&pit=55&alt=1.5

Looking good!
