### ISSUE TITLE
sf bottleneck

### ISSUE THREAD

**Issue by layik** [saferactive/saferactive-eatlas#19]
Currently `st_crop`ing 100k rows proves terribly slow. This is a placeholder to test R.data.table w/wo `sf`.

**Comment by Robinlovelace** [comment]
Good thinking - just needs something like:

```
dt_region = dt[lat >= bbox$latmin & lat < bbox$latmax & lon >= bbox$lonmin & lon < bbox$longmax]
```

That would be v. fast. `sf` is not efficient for point objects.

**Comment by layik** [comment]
Glad you see it the same @Robinlovelace. I bet that beats MongoDB/PosgreSQL but happy to be proven wrong.

Just need to disassemble current Rds for that to happen, unless we already have the lat longs left in the table, but in future we may hold off conversion to `sf`. Maybe even look at Dave et al's `sfheaders` to avoid sf all together when getting `json` sent over to the front/client.

**Comment by layik** [comment]
I wonder, is `sf` efficient for non-point objects?

**Comment by layik** [comment]
Just to say, any commits attached to this issue will be temp just like the casualties datsaet itself.

**Comment by Robinlovelace** [comment]
> I wonder, is `sf` efficient for non-point objects?

Compared with `rgeos` yes. Otherwise depends on your application but for country-level datasets up to a few million features it's fine. I did find that the `qgisprocess` interface led to a 100 fold+ speed-up for one specific use case though: https://github.com/paleolimbot/qgisprocess/issues/26

**Comment by layik** [comment]
open if needed.
