### ISSUE TITLE
Show change over time

### ISSUE THREAD

**Issue by Robinlovelace** [saferactive/saferactive-eatlas#24]
And remove difficult-to-interpret box shown below:

![image](https://user-images.githubusercontent.com/1825120/102377746-eb5bde00-3fbc-11eb-9a6d-60e0767f0875.png)

**Comment by Robinlovelace** [comment]
Still there on the deployed app (just tested)

![image](https://user-images.githubusercontent.com/1825120/104118135-9cd10380-531e-11eb-92be-40e0a634174f.png)

**Comment by layik** [comment]
Wont be there in next push/pull.
