### ISSUE TITLE
Change default filter variable

### ISSUE THREAD

**Issue by Robinlovelace** [saferactive/saferactive-eatlas#25]
Currently they are:

![image](https://user-images.githubusercontent.com/1825120/103785984-c561b080-5033-11eb-9486-63e70d76c820.png)

Should be....

**Comment by layik** [comment]
@mem48 @PublicHealthDataGeek ping!

**Comment by layik** [comment]
What this of course needs, is just like the values of those columns a search bar to find the desired column which is best done as a PR to e-Atlas of course.

**Comment by layik** [comment]
Updating upstream https://github.com/layik/eAtlas/issues/16

**Comment by Robinlovelace** [comment]
As a starter for 10 can we remove ones that definitely not needed (Location, Accident ID)?

**Comment by PublicHealthDataGeek** [comment]
My initial thoughts re the variables below ( I have just copied all the STATS19 variables - I am not sure if you have included all of these Layik).  I think it depends on who the audience is meant to be.  If it is the public then I think most of the 'main filter' ones are correct.  For some of the secondary ones you need to know about the stats19 data to understand what the variables are actually indicating.  The same could be said for some of the main ones actually so perhaps I havent quite got that right.  A 'user friendlyt' description of what each variables shows would be good to 'pop up' e.g. casualty class v casualty type - not clear from the names why these would be different.  



name | action
-- | --
accident_severity | main filter
number_of_vehicles | main filter
number_of_casualtie | main filter
date | main filter
day_of_week | main filter
time | main filter
local_authority_dis | main filter
first_road_class | main filter
road_type | main filter
speed_limit | main filter
junction_detail | main filter
urban_or_rural_area | main filter
vehicle_type | main filter
casualty_class | main filter
casualty_severity | main filter
casualty_type | main filter
pedestrian_crossing | main filter
police_force | ? keep main filter
  |  
accident_index | secondary filter
longitude | secondary filter
latitude | secondary filter
local_authority_hig | secondary filter
first_road_number | secondary filter
junction_control | secondary filter
second_road_class | secondary filter
second_road_number | secondary filter
light_conditions | secondary filter
weather_conditions | secondary filter
road_surface_condit | secondary filter
special_conditions_ | secondary filter
carriageway_hazards | secondary filter
did_police_officer_ | secondary filter
lsoa_of_accident_lo | secondary filter
datetime | secondary filter
vehicle_reference | secondary filter
towing_and_articula | secondary filter
vehicle_manoeuvre | secondary filter
vehicle_location_re | secondary filter
junction_location | secondary filter
skidding_and_overtu | secondary filter
hit_object_in_carri | secondary filter
vehicle_leaving_car | secondary filter
hit_object_off_carr | secondary filter
first_point_of_impa | secondary filter
was_vehicle_left_ha | secondary filter
journey_purpose_of_ | secondary filter
sex_of_driver | secondary filter
age_of_driver | secondary filter
age_band_of_driver | secondary filter
engine_capacity_cc | secondary filter
propulsion_code | secondary filter
age_of_vehicle | secondary filter
driver_imd_decile | secondary filter
driver_home_area_ty | secondary filter
vehicle_imd_decile | secondary filter
sex_of_casualty | secondary filter
age_of_casualty | secondary filter
age_band_of_casualt | secondary filter
pedestrian_location | secondary filter
pedestrian_movement | secondary filter
car_passenger | secondary filter
bus_or_coach_passen | secondary filter
pedestrian_road_mai | secondary filter
casualty_home_area_ | secondary filter
casualty_imd_decile | secondary filter
  |  
location_easting_os | delete
location_northing_o | delete
vehicle_reference | delete
casualty_reference | delete
  |  
pedestrian_crossing | ? is this text detail one?

**Comment by layik** [comment]
Thank you both. Please let me know if this covers everything and is the "swiss army knife". I have considered few UI/UX options and I think this is the most concise both in terms of UI and code.
![Peek 2021-01-08 14-03](https://user-images.githubusercontent.com/408568/104024203-a9d4e200-51ba-11eb-94b5-84bf7d6fb917.gif)

It is upstream in eAtlas so will be merged here.

**Comment by layik** [comment]
Of course multi-everything
![image](https://user-images.githubusercontent.com/408568/104024555-32ec1900-51bb-11eb-8987-17970d2a7591.png)

**Comment by Robinlovelace** [comment]
Looks good @layik :+1: Is it easy to put this latest version on map.saferactive.org? Would be good to test there if so.

**Comment by layik** [comment]
Absolutely. Let me merge on eAtlas and then pull in here and then, you know could be automated, but pull the new Docker build from production.

**Comment by Robinlovelace** [comment]
Great. Also is it easy to 'turn off' the points below a certain zoom level. I suggest that anything bigger than the area of a neighbourhood or perhaps ~10,000 points could be switched off.

**Comment by PublicHealthDataGeek** [comment]
> Thank you both. Please let me know if this covers everything and is the "swiss army knife". I have considered few UI/UX options and I think this is the most concise both in terms of UI and code.
> ![Peek 2021-01-08 14-03](https://user-images.githubusercontent.com/408568/104024203-a9d4e200-51ba-11eb-94b5-84bf7d6fb917.gif)
> 
> It is upstream in eAtlas so will be merged here.

looks very good to me!

**Comment by Robinlovelace** [comment]
Awesome filtering capabilities. Documentation, possibly using lots of gifs, will be useful!

**Comment by layik** [comment]
Everything is so much easier with [UI Component Libraries](https://www.google.com/search?q=ui+component+library). Reducing the code by 100s of lines.

Will rebuild production and let you all play with it.

**Comment by Robinlovelace** [comment]
Sounds good!

**Comment by layik** [comment]
Delay is due to the jungle of docker build/github actions

**Comment by layik** [comment]
https://map.saferactive.org has the latest.

Many more tweaks & changes needed.

**Comment by layik** [comment]
I will use those prioritised variables by @PublicHealthDataGeek elsewhere in the app obviously if dataset includes them. 

The less of them we serve the faster the app for spatiotemporal analysis purposes.

**Comment by Robinlovelace** [comment]
Great progress! I had a play just now and it's looking good. Time to load is biggest blocker atm IMO, will comment on #18 with details. Overall, great start on the tweaks needed before we can start sharing this and eventually using it to inform road safety discussions and policies :rocket:

**Comment by layik** [comment]
Over-delivered even.
