### ISSUE TITLE
GH Docker build unreliable

### ISSUE THREAD

**Issue by layik** [saferactive/saferactive-eatlas#27]
Is it just me or GH is letting us down @Robinlovelace? Thinking about moving back to Dockerhub/Travis.

**Comment by layik** [comment]
This is real now with latest build succeeding. https://github.com/saferactive/saferactive-eatlas/commit/71be9ca592a5fe860aa3478f45bd6e053eb7864d

**Comment by Robinlovelace** [comment]
Still watching this. Thanks for all the work + updates @layik !

**Comment by layik** [comment]
I will close it in that case.
