### ISSUE TITLE
geojsonsf not available for 3.4

### ISSUE THREAD

**Issue by layik** [saferactive/saferactive-eatlas#4]
We might have to reluctantly discard the use of `geojsonsf` as removing it is easier than changing the Dockerfile.

**Comment by layik** [comment]
@Robinlovelace this will be a separate issue to watch out for.

**Comment by layik** [comment]
Right, having thought about this. The only way is forward. Dockerfile must be changed to get >= R 3.5

**Comment by Robinlovelace** [comment]
Code here may be of use: https://github.com/rocker-org/rocker-versioned2

Or even:

```
FROM rocker/geospatial
```

**Comment by layik** [comment]
Yes, I started with `geospatial` it is just too heavy to use. Will checkout `rockerversion2`

**Comment by layik** [comment]
So move on with Dockerfile changes and unwind this.
