### ISSUE TITLE
Make time slider show at least 5 years of data by default

### ISSUE THREAD

**Issue by Robinlovelace** [saferactive/saferactive-eatlas#41]
By default it shows 2015 by the looks of it:

![image](https://user-images.githubusercontent.com/1825120/129926214-63627c0b-4c1a-4301-ab99-35ac9e4c4c89.png)

I think it would be way better to show multiple and more recent data by default, e.g. 2015:2019.

I think this should be a quick fix and low hanging fruit. Up for giving it a bash @layik ?

**Comment by layik** [comment]
Though focus has shifted, it does show 5 years, the slider just defaults on min value but not filters.
