### ISSUE TITLE
Attribute graphs that change when you zoom

### ISSUE THREAD

**Issue by Robinlovelace** [saferactive/saferactive-eatlas#8]
Would this be possible? I recall it worked for the data for Leeds. When I tried zooming in the graphs on the right did not change though:

![image](https://user-images.githubusercontent.com/1825120/88314268-8e5d4400-cd0c-11ea-92ed-4423a2185072.png)

Overall, this is looking awesome. Very slick.

**Comment by layik** [comment]
The only thing left to to do here is to decide whether to keep the graph generator. In graph generator, not sure if state is synced but on the ones appearing on sidebar all should be now fully sync. Can close once that decision is made, must say graph generator tool is not fully stable just as eatlas itself is not.

**Comment by layik** [comment]
Graph generator kept inline with beta release of eAtlas, new issue can be created if needed.
